services:
  inventory-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for live reloading
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Keep data persistent
      - inventory_data:/app/data
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DB_PATH=/app/data/inventory.db
    # Override the default command to use development server
    command: npm run dev:backend
    # Enable TTY for better log output
    tty: true
    stdin_open: true
